version: "3.5"
services:
  mysql8:
    container_name: mysql-usama
    hostname: mysql
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - net-db
    

  mysql8admin:
    image: phpmyadmin/phpmyadmin
    container_name: mysqladmin-usama
    hostname: mysql8admin
    restart: always
    links:
      - mysql8:db
    ports:
      - 4000:80
    networks:
      - net-db

networks:
    net-db:
        external: true


